#!/usr/bin/env python3
"""Write the candidate shaders the 5.6.0 experiment measures, from real bundles.

The 5.5.0-vs-5.6.0 transplant answers *which file* costs the 15%. It does not
answer the question protean actually has, which is **what that file costs
protean**, because protean does not ship stock Mol\\*: it carries the
`isBackground` repair from backlog 40 (`viewer/src/molstar-patches.ts`), and
that repair restores the early return in front of the occlusion sample loop.

Those are two different regimes and they could easily disagree:

* **stock** — `isBackground` never fires on the transparent path, so the
  128-sample loop runs over every texel of the framebuffer. A per-sample
  overhead is paid on the whole frame.
* **patched** — the early return fires, and the loop runs only where it must.
  The same per-sample overhead is then paid on a small fraction of the frame,
  and should be a much smaller fraction of the capture.

`docs/backlog.md` item 40 currently reads the agreement between the sweep's
15.2% step and the patched build's 15.4% residual as confirmation that the
patch removes none of the 5.6.0 cost. That agreement is across those two
regimes, so it is only meaningful if the loop is the same share of a capture in
both — and after the patch it plainly is not, or the patch would have bought far
more than 2.72x. The pair of files this writes is how that gets measured instead
of argued.

Each output is one release's shader with **only** the `isBackground` predicate
replaced, by exactly the substitution `viewer/src/molstar-patches.ts` performs —
upstream's own constant, and for `ssao-blur.frag` the 16-bit constant Mol\\*
itself used at 5.4.1, because that shader reads `packUnitIntervalToRG`'s
encoding rather than the depth texture.

Run it where the bundles are unpacked:

    python3 make_candidates.py --bundles-root bundles

The outputs are committed, because a measurement whose inputs are generated at
run time cannot be reproduced from the repository alone. Re-running this must
reproduce them byte for byte; `--check` asserts exactly that.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import shader_swap

HERE = Path(__file__).resolve().parent
OUT = HERE / "candidates"

# Verbatim from viewer/src/molstar-patches.ts. Not retyped from memory: the two
# constants differ because the two shaders read different encodings, and a
# previous version of that file used one constant for both, which made the patch
# a silent no-op on the blur.
BROKEN = """bool isBackground(const in float depth) {
    return depth == 1.0;
}"""

FIXED_24BIT = """bool isBackground(const in float depth) {
    // (2^24 - 1) / 2^24, max of 24-bit packed depth; also passes raw fp32.
    return depth >= 0.99999994;
}"""

FIXED_16BIT = """bool isBackground(const in float depth) {
    // Reads packUnitIntervalToRG's 16-bit encoding, not the 24-bit depth
    // texture: a background texel round-trips to 0.99998468, so the 24-bit
    // constant cannot fire here. This is what Mol* itself used at 5.4.1.
    return depth >= 0.999;
}"""

# (output name, source release, shader, replacement predicate)
CANDIDATES = [
    ("ssao-5.5.0-bgfix.frag", "5.5.0", "ssao.frag", FIXED_24BIT),
    ("ssao-5.6.0-bgfix.frag", "5.6.0", "ssao.frag", FIXED_24BIT),
    ("ssao-blur-bgfix.frag", "5.6.0", "ssao-blur.frag", FIXED_16BIT),
]

# No backticks anywhere in this, ever: the file is spliced into a JavaScript
# template literal, and one backtick would end it, producing a syntax error
# three megabytes from its cause. tests/test_shader_swap.py asserts it, and
# caught this header the first time it was written.
HEADER = """// GENERATED by bench/molstar-capture/make_candidates.py -- do not hand-edit.
//
// Mol* {version}'s {shader}, with the isBackground predicate replaced by the
// repair protean ships in viewer/src/molstar-patches.ts, and nothing else
// changed. Measured through --shader-swap {shader}=@<this file> so that the
// cost of {shader}'s body can be read in the regime protean actually runs in,
// where the early return in front of the sample loop fires.
"""


def build(bundles_root: Path) -> dict[str, str]:
    out = {}
    for name, version, shader, fixed in CANDIDATES:
        bundle, _ = shader_swap.resolve_source(version, bundles_root)
        glsl = shader_swap.read_shader(bundle, shader)
        if BROKEN not in glsl:
            raise shader_swap.SwapError(
                f"{version} {shader} does not carry the broken predicate; "
                "either the version is wrong or Mol* has fixed it and this "
                "experiment no longer means what it says"
            )
        patched = glsl.replace(BROKEN, fixed)
        if patched == glsl:
            raise shader_swap.SwapError(f"substitution changed nothing in {name}")
        out[name] = HEADER.format(version=version, shader=shader) + patched
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bundles-root", type=Path, default=Path("bundles"))
    ap.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed files are not what this would write",
    )
    args = ap.parse_args()

    built = build(args.bundles_root.resolve())
    OUT.mkdir(exist_ok=True)
    for name, text in built.items():
        path = OUT / name
        if args.check:
            if not path.is_file() or path.read_text() != text:
                print(f"{path} is not what make_candidates.py would write")
                return 1
            print(f"ok  {path}")
        else:
            path.write_text(text)
            print(f"wrote {path} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
